export type ConfigSectionId =
  | 'connectivity'
  | 'network'
  | 'logging'
  | 'quota'
  | 'streaming'
  | 'providers'
  | 'advanced'
  | 'payload';

export type ConfigFieldType =
  | 'switch'
  | 'string'
  | 'number'
  | 'select'
  | 'api_keys'
  | 'string_list'
  | 'textarea'
  | 'json_editor';

export interface ConfigFieldOption {
  /** The picker's key. */
  value: string;
  labelKey: string;
  /**
   * The value written to CPA when it is not the key itself. CPA reads some settings as either a
   * boolean or a word (`disable-image-generation: false | true | "chat" | "passthrough"`), and the
   * picker's keys are strings, so the boolean states name their YAML value here.
   */
  yamlValue?: unknown;
}

export interface ConfigFieldDefinition {
  id: string;
  sectionId: ConfigSectionId;
  labelKey: string;
  descKey: string;
  /** The canonical path in CPA's current v8 configuration tree. */
  yamlPath: string[];
  /** Earlier v8 layout; also the compatible write path when neither spelling is present. */
  legacyYamlPath?: string[];
  type: ConfigFieldType;
  scalarEndpointKey?: string;
  defaultValue?: unknown;
  placeholderKey?: string;
  unitKey?: string;
  min?: number;
  max?: number;
  options?: ConfigFieldOption[];
  keywords?: string[];
}

export const CONFIG_SECTIONS: { id: ConfigSectionId; labelKey: string; icon: string; descKey: string }[] = [
  { id: 'connectivity', labelKey: 'cfg.sec_connectivity', icon: 'KeyOutlined', descKey: 'cfg.sec_connectivity_desc' },
  { id: 'network', labelKey: 'cfg.sec_network', icon: 'GlobalOutlined', descKey: 'cfg.sec_network_desc' },
  { id: 'logging', labelKey: 'cfg.sec_logging', icon: 'ProfileOutlined', descKey: 'cfg.sec_logging_desc' },
  { id: 'quota', labelKey: 'cfg.sec_quota', icon: 'FieldTimeOutlined', descKey: 'cfg.sec_quota_desc' },
  { id: 'streaming', labelKey: 'cfg.sec_streaming', icon: 'NodeIndexOutlined', descKey: 'cfg.sec_streaming_desc' },
  { id: 'providers', labelKey: 'cfg.sec_providers', icon: 'ApiOutlined', descKey: 'cfg.sec_providers_desc' },
  { id: 'advanced', labelKey: 'cfg.sec_advanced', icon: 'ExperimentOutlined', descKey: 'cfg.sec_advanced_desc' },
  { id: 'payload', labelKey: 'cfg.sec_payload', icon: 'CodeOutlined', descKey: 'cfg.sec_payload_desc' },
];

export interface ConfigGroupDefinition {
  id: string;
  sectionId: ConfigSectionId;
  labelKey: string;
  descKey?: string;
  variant: 'form-grid' | 'settings-list' | 'managed-elsewhere' | 'tls-accordion' | 'payload-builder';
  fieldIds: string[];
}

export const CONFIG_GROUPS: ConfigGroupDefinition[] = [
  // ── 1. Connectivity & auth ──────────────────────────────────────────
  {
    id: 'grp_service',
    sectionId: 'connectivity',
    labelKey: 'cfg.grp_service',
    descKey: 'cfg.grp_service_desc',
    variant: 'form-grid',
    fieldIds: ['host', 'port', 'authDir', 'trustedProxies'],
  },
  {
    id: 'grp_apikeys',
    sectionId: 'connectivity',
    labelKey: 'cfg.grp_apikeys',
    descKey: 'cfg.grp_apikeys_desc',
    variant: 'managed-elsewhere',
    fieldIds: ['apiKeys'],
  },
  {
    id: 'grp_tls',
    sectionId: 'connectivity',
    labelKey: 'cfg.grp_tls',
    descKey: 'cfg.grp_tls_desc',
    variant: 'tls-accordion',
    fieldIds: ['tlsEnable', 'tlsCert', 'tlsKey'],
  },
  {
    id: 'grp_remote',
    sectionId: 'connectivity',
    labelKey: 'cfg.grp_remote',
    descKey: 'cfg.grp_remote_desc',
    variant: 'settings-list',
    fieldIds: ['rmAllowRemote', 'rmSecretKey', 'rmDisableControlPanel', 'rmDisableAutoUpdatePanel', 'rmPanelRepo', 'rmBaseUrl'],
  },

  // ── 2. Network ────────────────────────────────────────────────
  {
    id: 'grp_proxy_retry',
    sectionId: 'network',
    labelKey: 'cfg.grp_proxy_retry',
    descKey: 'cfg.grp_proxy_retry_desc',
    variant: 'form-grid',
    fieldIds: ['proxyUrl', 'requestRetry', 'maxRetryCredentials', 'maxRetryInterval', 'transientErrorCooldownSeconds', 'authAutoRefreshWorkers'],
  },
  {
    id: 'grp_routing_affinity',
    sectionId: 'network',
    labelKey: 'cfg.grp_routing_affinity',
    descKey: 'cfg.grp_routing_affinity_desc',
    variant: 'form-grid',
    fieldIds: ['routingStrategy', 'routingSessionAffinityTTL', 'routingSessionAffinity', 'routingSessionAffinitySubagents'],
  },
  {
    id: 'grp_network_flags',
    sectionId: 'network',
    labelKey: 'cfg.grp_network_flags',
    descKey: 'cfg.grp_network_flags_desc',
    variant: 'settings-list',
    fieldIds: ['disableImageGeneration', 'gptImage2BaseModel', 'videoResultAuthCacheTTL', 'forceModelPrefix', 'passthroughHeaders', 'disableCooling', 'saveCooldownStatus', 'wsAuth'],
  },

  // ── 3. Logging & diagnostics ──────────────────────────────────────────────
  {
    id: 'grp_logging_mode',
    sectionId: 'logging',
    labelKey: 'cfg.grp_logging_mode',
    descKey: 'cfg.grp_logging_mode_desc',
    variant: 'settings-list',
    fieldIds: ['debug', 'commercialMode', 'requestLog', 'loggingToFile', 'usageStatisticsEnabled'],
  },
  {
    id: 'grp_logging_storage',
    sectionId: 'logging',
    labelKey: 'cfg.grp_logging_storage',
    descKey: 'cfg.grp_logging_storage_desc',
    variant: 'form-grid',
    fieldIds: ['logsMaxTotalSizeMb', 'errorLogsMaxFiles', 'redisUsageQueueRetentionSeconds'],
  },

  // ── 4. Quota fallback ──────────────────────────────────────────────────
  {
    id: 'grp_quota_strategy',
    sectionId: 'quota',
    labelKey: 'cfg.grp_quota_strategy',
    descKey: 'cfg.grp_quota_strategy_desc',
    variant: 'settings-list',
    fieldIds: ['quotaSwitchProject', 'quotaSwitchPreviewModel', 'quotaAntigravityCredits'],
  },

  // ── 5. Streaming ──────────────────────────────────────────────
  {
    id: 'grp_streaming_transport',
    sectionId: 'streaming',
    labelKey: 'cfg.grp_streaming_transport',
    descKey: 'cfg.grp_streaming_transport_desc',
    variant: 'form-grid',
    fieldIds: ['streamingKeepaliveSeconds', 'streamingBootstrapRetries', 'streamingNonstreamKeepalive'],
  },

  // ── 6. OAuth provider behaviour ──────────────────────────────────────────
  //
  // `oauth.providers.<provider>` applies to OAuth/file-backed credentials only; an
  // API-key provider carries its own options in its `api-keys` group.
  {
    id: 'grp_codex_behavior',
    sectionId: 'providers',
    labelKey: 'cfg.grp_codex_behavior',
    descKey: 'cfg.grp_codex_behavior_desc',
    variant: 'settings-list',
    fieldIds: [
      'codexResponseSteering',
      'codexIdentityConfuse',
      'codexDisableCloaking',
      'codexOptimizeMultiAgentV2',
      'codexOrphanDelegationCompatibility',
      'codexModelLevelCooling',
      'codexStreamBootstrapBuffering',
      'codexStreamBootstrapTimeout',
    ],
  },
  {
    id: 'grp_codex_live_relay',
    sectionId: 'providers',
    labelKey: 'cfg.grp_codex_live_relay',
    descKey: 'cfg.grp_codex_live_relay_desc',
    variant: 'settings-list',
    fieldIds: ['codexLiveEnabled', 'codexLiveMaxSessions', 'codexLiveDisablePrivateRemoteIps', 'codexLivePublicIp', 'codexLiveUdpPortMin', 'codexLiveUdpPortMax'],
  },
  {
    id: 'grp_codex_headers',
    sectionId: 'providers',
    labelKey: 'cfg.grp_codex_headers',
    descKey: 'cfg.grp_codex_headers_desc',
    variant: 'form-grid',
    fieldIds: ['codexHeaderUserAgent', 'codexHeaderBetaFeatures'],
  },
  {
    id: 'grp_claude_behavior',
    sectionId: 'providers',
    labelKey: 'cfg.grp_claude_behavior',
    descKey: 'cfg.grp_claude_behavior_desc',
    variant: 'settings-list',
    fieldIds: ['claudeModelLevelCooling', 'claudeDisableCloakMode', 'claudeDisableCloakingModelList'],
  },
  {
    id: 'grp_claude_headers',
    sectionId: 'providers',
    labelKey: 'cfg.grp_claude_headers',
    descKey: 'cfg.grp_claude_headers_desc',
    variant: 'form-grid',
    fieldIds: ['claudeHeaderUserAgent', 'claudeHeaderPackageVersion', 'claudeHeaderRuntimeVersion', 'claudeHeaderOs', 'claudeHeaderArch', 'claudeHeaderTimeout', 'claudeHeaderTimezone', 'claudeHeaderStabilizeDeviceProfile'],
  },
  {
    id: 'grp_signature_cache',
    sectionId: 'providers',
    labelKey: 'cfg.grp_signature_cache',
    descKey: 'cfg.grp_signature_cache_desc',
    variant: 'settings-list',
    fieldIds: ['antigravitySignatureCacheEnabled', 'antigravitySignatureBypassStrict'],
  },
  {
    id: 'grp_antigravity_behavior',
    sectionId: 'providers',
    labelKey: 'cfg.grp_antigravity_behavior',
    descKey: 'cfg.grp_antigravity_behavior_desc',
    variant: 'settings-list',
    fieldIds: ['antigravityPoolEnabled', 'antigravityPoolIdleConnTimeout', 'antigravityPoolMaxIdleConnsPerHost', 'antigravitySensitiveWords'],
  },
  {
    id: 'grp_other_providers',
    sectionId: 'providers',
    labelKey: 'cfg.grp_other_providers',
    descKey: 'cfg.grp_other_providers_desc',
    variant: 'settings-list',
    fieldIds: ['xaiInjectXSearch', 'devinSensitiveWords'],
  },

  // ── 7. Advanced & experimental ────────────────────────────────────────────
  {
    id: 'grp_discovery',
    sectionId: 'advanced',
    labelKey: 'cfg.grp_discovery',
    descKey: 'cfg.grp_discovery_desc',
    variant: 'settings-list',
    fieldIds: ['discoveryEnabled', 'discoveryServiceName', 'discoveryAuthRequired', 'discoveryAdvertiseManagement'],
  },
  {
    id: 'grp_pprof',
    sectionId: 'advanced',
    labelKey: 'cfg.grp_pprof',
    descKey: 'cfg.grp_pprof_desc',
    variant: 'settings-list',
    fieldIds: ['pprofEnable', 'pprofAddr'],
  },

  // ── 8. Payload rules ────────────────────────────────────────────
  {
    id: 'grp_payload_rules',
    sectionId: 'payload',
    labelKey: 'cfg.grp_payload_rules',
    descKey: 'cfg.grp_payload_rules_desc',
    variant: 'payload-builder',
    fieldIds: ['payloadDefaultRules', 'payloadDefaultRawRules', 'payloadOverrideRules', 'payloadOverrideRawRules', 'payloadFilterRules'],
  },
];

export function getGroupsForSection(sectionId: ConfigSectionId): ConfigGroupDefinition[] {
  const groups = CONFIG_GROUPS.filter((g) => g.sectionId === sectionId);
  const groupedFieldIds = new Set(groups.flatMap((g) => g.fieldIds));
  const remainingFields = ALL_CONFIG_FIELDS.filter(
    (f) => f.sectionId === sectionId && !groupedFieldIds.has(f.id),
  );
  if (remainingFields.length > 0) {
    groups.push({
      id: `${sectionId}_other`,
      sectionId,
      labelKey: 'cfg.grp_other',
      descKey: 'cfg.grp_other_desc',
      variant: 'form-grid',
      fieldIds: remainingFields.map((f) => f.id),
    });
  }
  return groups;
}

export const ALL_CONFIG_FIELDS: ConfigFieldDefinition[] = [
  // ── 1. Connectivity & auth ──────────────────────────────────────────
  {
    id: 'host',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_host',
    descKey: 'cfg.f_host_desc',
    yamlPath: ['server', 'host'],
    type: 'string',
    placeholderKey: 'cfg.f_host_placeholder',
    keywords: ['host', 'ip', 'bind', 'server'],
  },
  {
    id: 'port',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_port',
    descKey: 'cfg.f_port_desc',
    yamlPath: ['server', 'port'],
    type: 'number',
    min: 1,
    max: 65535,
    defaultValue: 8317,
    keywords: ['port', 'listen'],
  },
  {
    id: 'authDir',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_auth_dir',
    descKey: 'cfg.f_auth_dir_desc',
    yamlPath: ['oauth', 'auth-dir'],
    type: 'string',
    placeholderKey: '~/.cli-proxy-api',
    keywords: ['auth', 'dir', 'directory'],
  },
  {
    id: 'apiKeys',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_api_keys',
    descKey: 'cfg.f_api_keys_desc',
    yamlPath: ['access', 'api-keys'],
    type: 'api_keys',
    defaultValue: [],
    keywords: ['api-key', 'apikey', 'token', 'secret'],
  },
  {
    id: 'tlsEnable',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_tls_enable',
    descKey: 'cfg.f_tls_enable_desc',
    yamlPath: ['server', 'tls', 'enable'],
    type: 'switch',
    defaultValue: false,
    keywords: ['tls', 'ssl', 'https'],
  },
  {
    id: 'tlsCert',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_tls_cert',
    descKey: 'cfg.f_tls_cert_desc',
    yamlPath: ['server', 'tls', 'cert'],
    type: 'string',
    keywords: ['tls', 'cert', 'certificate'],
  },
  {
    id: 'tlsKey',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_tls_key',
    descKey: 'cfg.f_tls_key_desc',
    yamlPath: ['server', 'tls', 'key'],
    type: 'string',
    keywords: ['tls', 'key', 'private'],
  },
  {
    id: 'rmAllowRemote',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_rm_allow_remote',
    descKey: 'cfg.f_rm_allow_remote_desc',
    yamlPath: ['management', 'allow-remote'],
    type: 'switch',
    defaultValue: false,
    keywords: ['remote', 'allow'],
  },
  {
    id: 'rmSecretKey',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_rm_secret_key',
    descKey: 'cfg.f_rm_secret_key_desc',
    yamlPath: ['management', 'secret-key'],
    type: 'string',
    keywords: ['management', 'secret', 'password'],
  },
  {
    id: 'rmDisableControlPanel',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_rm_disable_panel',
    descKey: 'cfg.f_rm_disable_panel_desc',
    yamlPath: ['management', 'disable-control-panel'],
    type: 'switch',
    defaultValue: false,
    keywords: ['panel', 'disable'],
  },
  {
    id: 'rmDisableAutoUpdatePanel',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_rm_disable_auto_update',
    descKey: 'cfg.f_rm_disable_auto_update_desc',
    yamlPath: ['management', 'disable-auto-update-panel'],
    type: 'switch',
    defaultValue: false,
    keywords: ['update', 'auto'],
  },
  {
    id: 'rmPanelRepo',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_rm_panel_repo',
    descKey: 'cfg.f_rm_panel_repo_desc',
    yamlPath: ['management', 'panel-github-repository'],
    type: 'string',
    placeholderKey: 'https://github.com/router-for-me/Cli-Proxy-API-Management-Center',
    keywords: ['repo', 'github'],
  },
  {
    id: 'trustedProxies',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_trusted_proxies',
    descKey: 'cfg.f_trusted_proxies_desc',
    yamlPath: ['server', 'trusted-proxies'],
    type: 'string_list',
    placeholderKey: '127.0.0.1, 192.0.2.0/24',
    keywords: ['proxy', 'trusted', 'forwarded', 'cidr', 'x-forwarded-for'],
  },
  {
    id: 'rmBaseUrl',
    sectionId: 'connectivity',
    labelKey: 'cfg.f_rm_base_url',
    descKey: 'cfg.f_rm_base_url_desc',
    yamlPath: ['management', 'base-url'],
    type: 'string',
    placeholderKey: 'https://proxy.example.com',
    keywords: ['management', 'tui', 'base-url'],
  },

  // ── 2. Network ────────────────────────────────────────────────
  {
    id: 'proxyUrl',
    sectionId: 'network',
    labelKey: 'cfg.proxy_url',
    descKey: 'cfg.proxy_url_desc',
    yamlPath: ['requests', 'proxy-url'],
    type: 'string',
    scalarEndpointKey: 'proxy_url',
    placeholderKey: 'cfg.proxy_url_placeholder',
    keywords: ['proxy', 'socks5', 'http'],
  },
  {
    id: 'requestRetry',
    sectionId: 'network',
    labelKey: 'cfg.request_retry',
    descKey: 'cfg.request_retry_desc',
    yamlPath: ['routing', 'retry', 'request-retry'],
    type: 'number',
    scalarEndpointKey: 'request_retry',
    min: 0,
    unitKey: 'cfg.unit_times',
    defaultValue: 0,
    keywords: ['retry', 'request'],
  },
  {
    id: 'maxRetryCredentials',
    sectionId: 'network',
    labelKey: 'cfg.max_retry_credentials',
    descKey: 'cfg.max_retry_credentials_desc',
    yamlPath: ['routing', 'retry', 'max-retry-credentials'],
    type: 'number',
    scalarEndpointKey: 'max_retry_credentials',
    min: 0,
    unitKey: 'cfg.unit_files',
    defaultValue: 0,
    keywords: ['retry', 'credential'],
  },
  {
    id: 'maxRetryInterval',
    sectionId: 'network',
    labelKey: 'cfg.max_retry_interval',
    descKey: 'cfg.max_retry_interval_desc',
    yamlPath: ['routing', 'retry', 'max-retry-interval'],
    type: 'number',
    scalarEndpointKey: 'max_retry_interval',
    min: 0,
    unitKey: 'cfg.unit_seconds',
    defaultValue: 0,
    keywords: ['retry', 'interval'],
  },
  {
    id: 'authAutoRefreshWorkers',
    sectionId: 'network',
    labelKey: 'cfg.f_auth_refresh_workers',
    descKey: 'cfg.f_auth_refresh_workers_desc',
    yamlPath: ['oauth', 'auth-auto-refresh-workers'],
    type: 'number',
    min: 0,
    unitKey: 'cfg.unit_files',
    defaultValue: 0,
    keywords: ['worker', 'refresh'],
  },
  {
    id: 'routingStrategy',
    sectionId: 'network',
    labelKey: 'cfg.routing_strategy',
    descKey: 'cfg.routing_strategy_desc',
    yamlPath: ['routing', 'strategy'],
    type: 'select',
    scalarEndpointKey: 'routing_strategy',
    defaultValue: 'round-robin',
    options: [
      { value: 'round-robin', labelKey: 'cfg.strategy_round_robin' },
      { value: 'weighted-round-robin', labelKey: 'cfg.strategy_wrr' },
      { value: 'fill-first', labelKey: 'cfg.strategy_fill_first' },
    ],
    keywords: ['routing', 'strategy', 'balance', 'load'],
  },
  {
    id: 'routingSessionAffinityTTL',
    sectionId: 'network',
    labelKey: 'cfg.f_affinity_ttl',
    descKey: 'cfg.f_affinity_ttl_desc',
    yamlPath: ['routing', 'session-affinity-ttl'],
    type: 'string',
    placeholderKey: '1h',
    keywords: ['affinity', 'session', 'ttl'],
  },
  {
    id: 'routingSessionAffinity',
    sectionId: 'network',
    labelKey: 'cfg.f_affinity',
    descKey: 'cfg.f_affinity_desc',
    yamlPath: ['routing', 'session-affinity'],
    type: 'switch',
    defaultValue: false,
    keywords: ['affinity', 'session'],
  },
  {
    id: 'disableImageGeneration',
    sectionId: 'network',
    labelKey: 'cfg.f_disable_image_gen',
    descKey: 'cfg.f_disable_image_gen_desc',
    yamlPath: ['multimedia', 'disable-image-generation'],
    type: 'select',
    defaultValue: false,
    options: [
      { value: 'false', labelKey: 'cfg.image_gen_enabled', yamlValue: false },
      { value: 'true', labelKey: 'cfg.image_gen_disabled', yamlValue: true },
      { value: 'chat', labelKey: 'cfg.image_gen_chat' },
      { value: 'passthrough', labelKey: 'cfg.image_gen_passthrough' },
    ],
    keywords: ['image', 'dall-e', 'chat', 'passthrough'],
  },
  {
    id: 'gptImage2BaseModel',
    sectionId: 'network',
    labelKey: 'cfg.f_gpt_image_model',
    descKey: 'cfg.f_gpt_image_model_desc',
    yamlPath: ['multimedia', 'gpt-image-2-base-model'],
    type: 'string',
    placeholderKey: 'gpt-5.4-mini',
    keywords: ['image', 'base64', 'model'],
  },
  {
    id: 'forceModelPrefix',
    sectionId: 'network',
    labelKey: 'cfg.force_model_prefix',
    descKey: 'cfg.force_model_prefix_desc',
    yamlPath: ['routing', 'force-model-prefix'],
    type: 'switch',
    scalarEndpointKey: 'force_model_prefix',
    defaultValue: false,
    keywords: ['model', 'prefix'],
  },
  {
    id: 'passthroughHeaders',
    sectionId: 'network',
    labelKey: 'cfg.f_passthrough_headers',
    descKey: 'cfg.f_passthrough_headers_desc',
    yamlPath: ['requests', 'passthrough-headers'],
    type: 'switch',
    defaultValue: false,
    keywords: ['header', 'passthrough'],
  },
  {
    id: 'disableCooling',
    sectionId: 'network',
    labelKey: 'cfg.f_disable_cooling',
    descKey: 'cfg.f_disable_cooling_desc',
    yamlPath: ['routing', 'cooldown', 'disable-cooling'],
    type: 'switch',
    defaultValue: false,
    keywords: ['cooling', 'cooldown'],
  },
  {
    id: 'wsAuth',
    sectionId: 'network',
    labelKey: 'cfg.ws_auth',
    descKey: 'cfg.ws_auth_desc',
    yamlPath: ['oauth', 'providers', 'aistudio', 'ws-auth'],
    type: 'switch',
    scalarEndpointKey: 'ws_auth',
    defaultValue: true,
    keywords: ['ws', 'websocket', 'auth'],
  },
  {
    id: 'transientErrorCooldownSeconds',
    sectionId: 'network',
    labelKey: 'cfg.f_transient_cooldown',
    descKey: 'cfg.f_transient_cooldown_desc',
    // 0 keeps CPA's legacy 60-second cooldown and -1 turns it off, so the floor is -1.
    yamlPath: ['routing', 'cooldown', 'transient-error-cooldown-seconds'],
    type: 'number',
    min: -1,
    unitKey: 'cfg.unit_seconds',
    defaultValue: 0,
    keywords: ['cooldown', 'transient', '5xx', 'error'],
  },
  {
    id: 'routingSessionAffinitySubagents',
    sectionId: 'network',
    labelKey: 'cfg.f_affinity_subagents',
    descKey: 'cfg.f_affinity_subagents_desc',
    yamlPath: ['routing', 'session-affinity-subagents'],
    type: 'switch',
    defaultValue: true,
    keywords: ['affinity', 'subagent', 'session'],
  },
  {
    id: 'videoResultAuthCacheTTL',
    sectionId: 'network',
    labelKey: 'cfg.f_video_ttl',
    descKey: 'cfg.f_video_ttl_desc',
    yamlPath: ['multimedia', 'video-result-auth-cache-ttl'],
    type: 'string',
    placeholderKey: '3h',
    keywords: ['video', 'ttl', 'cache'],
  },
  {
    id: 'saveCooldownStatus',
    sectionId: 'network',
    labelKey: 'cfg.f_save_cooldown_status',
    descKey: 'cfg.f_save_cooldown_status_desc',
    yamlPath: ['routing', 'cooldown', 'save-cooldown-status'],
    type: 'switch',
    defaultValue: false,
    keywords: ['cooldown', 'persist', 'cds'],
  },

  // ── 3. Logging & diagnostics ──────────────────────────────────────────────
  {
    id: 'debug',
    sectionId: 'logging',
    labelKey: 'cfg.debug',
    descKey: 'cfg.debug_desc',
    yamlPath: ['observability', 'logs', 'debug'],
    type: 'switch',
    scalarEndpointKey: 'debug',
    defaultValue: false,
    keywords: ['debug', 'log', 'verbose'],
  },
  {
    id: 'commercialMode',
    sectionId: 'logging',
    labelKey: 'cfg.f_commercial_mode',
    descKey: 'cfg.f_commercial_mode_desc',
    yamlPath: ['server', 'commercial-mode'],
    type: 'switch',
    defaultValue: false,
    keywords: ['commercial', 'mode'],
  },
  {
    id: 'requestLog',
    sectionId: 'logging',
    labelKey: 'cfg.request_log',
    descKey: 'cfg.request_log_desc',
    yamlPath: ['observability', 'logs', 'request-log'],
    type: 'switch',
    scalarEndpointKey: 'request_log',
    defaultValue: false,
    keywords: ['request', 'log'],
  },
  {
    id: 'loggingToFile',
    sectionId: 'logging',
    labelKey: 'cfg.logging_to_file',
    descKey: 'cfg.logging_to_file_desc',
    yamlPath: ['observability', 'logs', 'logging-to-file'],
    type: 'switch',
    scalarEndpointKey: 'logging_to_file',
    defaultValue: false,
    keywords: ['file', 'log', 'tail'],
  },
  {
    id: 'logsMaxTotalSizeMb',
    sectionId: 'logging',
    labelKey: 'cfg.logs_max_total_size_mb',
    descKey: 'cfg.logs_max_total_size_mb_desc',
    yamlPath: ['observability', 'logs', 'logs-max-total-size-mb'],
    type: 'number',
    scalarEndpointKey: 'logs_max_total_size_mb',
    min: 0,
    unitKey: 'cfg.unit_mb',
    defaultValue: 0,
    keywords: ['size', 'mb', 'log'],
  },
  {
    id: 'errorLogsMaxFiles',
    sectionId: 'logging',
    labelKey: 'cfg.error_logs_max_files',
    descKey: 'cfg.error_logs_max_files_desc',
    yamlPath: ['observability', 'logs', 'error-logs-max-files'],
    type: 'number',
    scalarEndpointKey: 'error_logs_max_files',
    min: 0,
    unitKey: 'cfg.unit_files',
    defaultValue: 10,
    keywords: ['error', 'file', 'log'],
  },
  {
    id: 'redisUsageQueueRetentionSeconds',
    sectionId: 'logging',
    labelKey: 'cfg.f_redis_retention',
    descKey: 'cfg.f_redis_retention_desc',
    yamlPath: ['observability', 'usage', 'redis-usage-queue-retention-seconds'],
    type: 'number',
    min: 0,
    max: 3600,
    unitKey: 'cfg.unit_seconds',
    defaultValue: 60,
    keywords: ['redis', 'queue', 'retention'],
  },
  {
    id: 'usageStatisticsEnabled',
    sectionId: 'logging',
    labelKey: 'cfg.usage_statistics_enabled',
    descKey: 'cfg.usage_statistics_enabled_desc',
    yamlPath: ['observability', 'usage', 'usage-statistics-enabled'],
    type: 'switch',
    scalarEndpointKey: 'usage_statistics_enabled',
    defaultValue: false,
    keywords: ['usage', 'stats', 'token'],
  },

  // ── 4. Quota fallback ──────────────────────────────────────────────────
  {
    id: 'quotaSwitchProject',
    sectionId: 'quota',
    labelKey: 'cfg.f_switch_project',
    descKey: 'cfg.f_switch_project_desc',
    yamlPath: ['quota-exceeded', 'switch-project'],
    type: 'switch',
    defaultValue: false,
    keywords: ['quota', 'project', 'switch'],
  },
  {
    id: 'quotaSwitchPreviewModel',
    sectionId: 'quota',
    labelKey: 'cfg.f_switch_preview_model',
    descKey: 'cfg.f_switch_preview_model_desc',
    yamlPath: ['quota-exceeded', 'switch-preview-model'],
    type: 'switch',
    defaultValue: false,
    keywords: ['quota', 'preview', 'model'],
  },
  {
    id: 'quotaAntigravityCredits',
    sectionId: 'quota',
    labelKey: 'cfg.f_antigravity_credits',
    descKey: 'cfg.f_antigravity_credits_desc',
    yamlPath: ['oauth', 'providers', 'antigravity', 'antigravity-credits'],
    type: 'switch',
    defaultValue: false,
    keywords: ['antigravity', 'credits'],
  },

  // ── 5. Streaming ──────────────────────────────────────────
  {
    id: 'streamingKeepaliveSeconds',
    sectionId: 'streaming',
    labelKey: 'cfg.f_keepalive_sec',
    descKey: 'cfg.f_keepalive_sec_desc',
    yamlPath: ['requests', 'streaming', 'keepalive-seconds'],
    type: 'number',
    min: 0,
    unitKey: 'cfg.unit_seconds',
    defaultValue: 0,
    keywords: ['stream', 'keepalive', 'sse'],
  },
  {
    id: 'streamingBootstrapRetries',
    sectionId: 'streaming',
    labelKey: 'cfg.f_bootstrap_retries',
    descKey: 'cfg.f_bootstrap_retries_desc',
    yamlPath: ['requests', 'streaming', 'bootstrap-retries'],
    type: 'number',
    min: 0,
    unitKey: 'cfg.unit_times',
    defaultValue: 0,
    keywords: ['stream', 'bootstrap', 'retry'],
  },
  {
    id: 'streamingNonstreamKeepalive',
    sectionId: 'streaming',
    labelKey: 'cfg.f_nonstream_keepalive',
    descKey: 'cfg.f_nonstream_keepalive_desc',
    // Beside `streaming`, not inside it, and a whole number of seconds: CPA
    // rejects a duration string such as "30s".
    yamlPath: ['requests', 'nonstream-keepalive-interval'],
    type: 'number',
    min: 0,
    unitKey: 'cfg.unit_seconds',
    defaultValue: 0,
    keywords: ['stream', 'nonstream', 'keepalive'],
  },

  // ── 6. OAuth provider behaviour ──────────────────────────────────────────
  {
    id: 'antigravitySignatureCacheEnabled',
    sectionId: 'providers',
    labelKey: 'cfg.f_sig_cache',
    descKey: 'cfg.f_sig_cache_desc',
    // CPA treats an absent value as on.
    yamlPath: ['oauth', 'providers', 'antigravity', 'signature-cache-enabled'],
    type: 'switch',
    defaultValue: true,
    keywords: ['signature', 'cache', 'antigravity'],
  },
  {
    id: 'antigravitySignatureBypassStrict',
    sectionId: 'providers',
    labelKey: 'cfg.f_sig_strict',
    descKey: 'cfg.f_sig_strict_desc',
    yamlPath: ['oauth', 'providers', 'antigravity', 'signature-bypass-strict'],
    type: 'switch',
    defaultValue: false,
    keywords: ['signature', 'strict', 'bypass'],
  },
  {
    id: 'claudeHeaderUserAgent',
    sectionId: 'providers',
    labelKey: 'cfg.f_claude_ua',
    descKey: 'cfg.f_claude_ua_desc',
    yamlPath: ['oauth', 'providers', 'claude', 'header-defaults', 'user-agent'],
    type: 'string',
    keywords: ['claude', 'user-agent', 'header'],
  },
  {
    id: 'claudeHeaderPackageVersion',
    sectionId: 'providers',
    labelKey: 'cfg.f_claude_pkg',
    descKey: 'cfg.f_claude_pkg_desc',
    yamlPath: ['oauth', 'providers', 'claude', 'header-defaults', 'package-version'],
    type: 'string',
    keywords: ['claude', 'version'],
  },
  {
    id: 'claudeHeaderRuntimeVersion',
    sectionId: 'providers',
    labelKey: 'cfg.f_claude_runtime',
    descKey: 'cfg.f_claude_runtime_desc',
    yamlPath: ['oauth', 'providers', 'claude', 'header-defaults', 'runtime-version'],
    type: 'string',
    keywords: ['claude', 'runtime'],
  },
  {
    id: 'claudeHeaderOs',
    sectionId: 'providers',
    labelKey: 'cfg.f_claude_os',
    descKey: 'cfg.f_claude_os_desc',
    yamlPath: ['oauth', 'providers', 'claude', 'header-defaults', 'os'],
    type: 'string',
    keywords: ['claude', 'os'],
  },
  {
    id: 'claudeHeaderArch',
    sectionId: 'providers',
    labelKey: 'cfg.f_claude_arch',
    descKey: 'cfg.f_claude_arch_desc',
    yamlPath: ['oauth', 'providers', 'claude', 'header-defaults', 'arch'],
    type: 'string',
    keywords: ['claude', 'arch'],
  },
  {
    id: 'claudeHeaderTimeout',
    sectionId: 'providers',
    labelKey: 'cfg.f_claude_timeout',
    descKey: 'cfg.f_claude_timeout_desc',
    yamlPath: ['oauth', 'providers', 'claude', 'header-defaults', 'timeout'],
    type: 'string',
    keywords: ['claude', 'timeout'],
  },
  {
    id: 'claudeHeaderStabilizeDeviceProfile',
    sectionId: 'providers',
    labelKey: 'cfg.f_claude_stabilize',
    descKey: 'cfg.f_claude_stabilize_desc',
    yamlPath: ['oauth', 'providers', 'claude', 'header-defaults', 'stabilize-device-profile'],
    type: 'switch',
    defaultValue: false,
    keywords: ['claude', 'device', 'fingerprint'],
  },
  {
    id: 'codexHeaderUserAgent',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_ua',
    descKey: 'cfg.f_codex_ua_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'header-defaults', 'user-agent'],
    type: 'string',
    keywords: ['codex', 'user-agent'],
  },
  {
    id: 'codexHeaderBetaFeatures',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_beta',
    descKey: 'cfg.f_codex_beta_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'header-defaults', 'beta-features'],
    type: 'string',
    keywords: ['codex', 'beta'],
  },
  {
    id: 'codexResponseSteering',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_response_steering',
    descKey: 'cfg.f_codex_response_steering_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'response-steering'],
    type: 'switch',
    defaultValue: false,
    keywords: ['codex', 'websocket', 'steering'],
  },
  {
    id: 'codexIdentityConfuse',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_identity_confuse',
    descKey: 'cfg.f_codex_identity_confuse_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'identity-confuse'],
    type: 'switch',
    defaultValue: false,
    keywords: ['codex', 'identity', 'prompt_cache_key'],
  },
  {
    id: 'codexDisableCloaking',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_disable_cloaking',
    descKey: 'cfg.f_codex_disable_cloaking_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'disable-codex-cloaking'],
    type: 'switch',
    defaultValue: false,
    keywords: ['codex', 'cloak', 'user-agent', 'originator'],
  },
  {
    id: 'codexOptimizeMultiAgentV2',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_multi_agent_v2',
    descKey: 'cfg.f_codex_multi_agent_v2_desc',
    yamlPath: ['client', 'codex', 'optimize-multi-agent-v2'],
    legacyYamlPath: ['oauth', 'providers', 'codex', 'optimize-multi-agent-v2'],
    type: 'switch',
    defaultValue: false,
    keywords: ['codex', 'multi-agent', 'agent'],
  },
  {
    id: 'codexOrphanDelegationCompatibility',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_orphan_delegation',
    descKey: 'cfg.f_codex_orphan_delegation_desc',
    yamlPath: ['upstream', 'codex', 'orphan-delegation-compatibility'],
    legacyYamlPath: ['oauth', 'providers', 'codex', 'orphan-delegation-compatibility'],
    type: 'switch',
    defaultValue: false,
    keywords: ['codex', 'orphan', 'delegation', 'subagent'],
  },
  {
    id: 'codexModelLevelCooling',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_model_cooling',
    descKey: 'cfg.f_codex_model_cooling_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'model-level-cooling'],
    type: 'switch',
    defaultValue: false,
    keywords: ['codex', 'cooling', 'quota', 'model'],
  },
  {
    id: 'codexStreamBootstrapBuffering',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_bootstrap_buffering',
    descKey: 'cfg.f_codex_bootstrap_buffering_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'stream-bootstrap-buffering'],
    type: 'switch',
    defaultValue: false,
    keywords: ['codex', 'stream', 'bootstrap', 'overload', 'failover'],
  },
  {
    id: 'codexStreamBootstrapTimeout',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_bootstrap_timeout',
    descKey: 'cfg.f_codex_bootstrap_timeout_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'stream-bootstrap-timeout'],
    type: 'string',
    placeholderKey: '0',
    keywords: ['codex', 'stream', 'bootstrap', 'timeout'],
  },
  // CPA's JSON view redacts TURN secrets but preserves omitted ones on writes
  // with matching URL arrays. ICE editing needs explicit keep/replace/clear states.
  {
    id: 'codexLiveEnabled',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_live_enabled',
    descKey: 'cfg.f_codex_live_enabled_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'live-media-relay', 'enabled'],
    type: 'switch',
    defaultValue: false,
    keywords: ['codex', 'live', 'webrtc', 'media', 'relay'],
  },
  {
    id: 'codexLiveMaxSessions',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_live_max_sessions',
    descKey: 'cfg.f_codex_live_max_sessions_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'live-media-relay', 'max-sessions'],
    type: 'number',
    min: 0,
    defaultValue: 32,
    keywords: ['codex', 'live', 'sessions'],
  },
  {
    id: 'codexLiveDisablePrivateRemoteIps',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_live_private_ips',
    descKey: 'cfg.f_codex_live_private_ips_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'live-media-relay', 'disable-private-remote-ips'],
    type: 'switch',
    defaultValue: false,
    keywords: ['codex', 'live', 'sdp', 'private', 'ip'],
  },
  {
    id: 'codexLivePublicIp',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_live_public_ip',
    descKey: 'cfg.f_codex_live_public_ip_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'live-media-relay', 'public-ip'],
    type: 'string',
    placeholderKey: '203.0.113.10',
    keywords: ['codex', 'live', 'nat', 'public', 'ip'],
  },
  {
    id: 'codexLiveUdpPortMin',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_live_udp_min',
    descKey: 'cfg.f_codex_live_udp_range_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'live-media-relay', 'udp-port-min'],
    type: 'number',
    min: 0,
    max: 65535,
    defaultValue: 0,
    keywords: ['codex', 'live', 'udp', 'port'],
  },
  {
    id: 'codexLiveUdpPortMax',
    sectionId: 'providers',
    labelKey: 'cfg.f_codex_live_udp_max',
    descKey: 'cfg.f_codex_live_udp_range_desc',
    yamlPath: ['oauth', 'providers', 'codex', 'live-media-relay', 'udp-port-max'],
    type: 'number',
    min: 0,
    max: 65535,
    defaultValue: 0,
    keywords: ['codex', 'live', 'udp', 'port'],
  },
  {
    id: 'claudeModelLevelCooling',
    sectionId: 'providers',
    labelKey: 'cfg.f_claude_model_cooling',
    descKey: 'cfg.f_claude_model_cooling_desc',
    yamlPath: ['oauth', 'providers', 'claude', 'model-level-cooling'],
    type: 'switch',
    defaultValue: false,
    keywords: ['claude', 'cooling', 'quota', 'model'],
  },
  {
    id: 'claudeDisableCloakMode',
    sectionId: 'providers',
    labelKey: 'cfg.f_claude_disable_cloak',
    descKey: 'cfg.f_claude_disable_cloak_desc',
    yamlPath: ['oauth', 'providers', 'claude', 'disable-claude-cloak-mode'],
    type: 'switch',
    defaultValue: false,
    keywords: ['claude', 'cloak', 'system prompt'],
  },
  {
    id: 'claudeDisableCloakingModelList',
    sectionId: 'providers',
    labelKey: 'cfg.f_claude_cloaking_model_list',
    descKey: 'cfg.f_claude_cloaking_model_list_desc',
    yamlPath: ['oauth', 'providers', 'claude', 'claude-code', 'disable-cloaking-model-list'],
    type: 'switch',
    defaultValue: false,
    keywords: ['claude', 'claude-code', 'model list', 'cloak'],
  },
  {
    id: 'claudeHeaderTimezone',
    sectionId: 'providers',
    labelKey: 'cfg.f_claude_timezone',
    descKey: 'cfg.f_claude_timezone_desc',
    yamlPath: ['oauth', 'providers', 'claude', 'header-defaults', 'timezone'],
    type: 'string',
    placeholderKey: 'Asia/Singapore',
    keywords: ['claude', 'timezone', 'currentDate'],
  },
  {
    id: 'antigravityPoolEnabled',
    sectionId: 'providers',
    labelKey: 'cfg.f_ag_pool_enabled',
    descKey: 'cfg.f_ag_pool_enabled_desc',
    yamlPath: ['oauth', 'providers', 'antigravity', 'connection-pool', 'enabled'],
    type: 'switch',
    defaultValue: false,
    keywords: ['antigravity', 'connection', 'pool'],
  },
  {
    id: 'antigravityPoolIdleConnTimeout',
    sectionId: 'providers',
    labelKey: 'cfg.f_ag_pool_idle_timeout',
    descKey: 'cfg.f_ag_pool_idle_timeout_desc',
    yamlPath: ['oauth', 'providers', 'antigravity', 'connection-pool', 'idle-conn-timeout'],
    type: 'string',
    placeholderKey: '30s',
    keywords: ['antigravity', 'idle', 'timeout', 'keep-alive'],
  },
  {
    id: 'antigravityPoolMaxIdleConnsPerHost',
    sectionId: 'providers',
    labelKey: 'cfg.f_ag_pool_max_idle',
    descKey: 'cfg.f_ag_pool_max_idle_desc',
    yamlPath: ['oauth', 'providers', 'antigravity', 'connection-pool', 'max-idle-conns-per-host'],
    type: 'number',
    min: 0,
    defaultValue: 2,
    keywords: ['antigravity', 'idle', 'connections'],
  },
  {
    id: 'antigravitySensitiveWords',
    sectionId: 'providers',
    labelKey: 'cfg.f_ag_sensitive_words',
    descKey: 'cfg.f_ag_sensitive_words_desc',
    yamlPath: ['oauth', 'providers', 'antigravity', 'sensitive-words'],
    type: 'string_list',
    placeholderKey: 'cfg.string_list_placeholder',
    keywords: ['antigravity', 'sensitive', 'words', 'obfuscate'],
  },
  {
    id: 'xaiInjectXSearch',
    sectionId: 'providers',
    labelKey: 'cfg.f_xai_inject_search',
    descKey: 'cfg.f_xai_inject_search_desc',
    yamlPath: ['oauth', 'providers', 'xai', 'inject-x-search'],
    type: 'switch',
    defaultValue: false,
    keywords: ['xai', 'grok', 'x_search', 'search'],
  },
  {
    id: 'devinSensitiveWords',
    sectionId: 'providers',
    labelKey: 'cfg.f_devin_sensitive_words',
    descKey: 'cfg.f_devin_sensitive_words_desc',
    yamlPath: ['oauth', 'providers', 'devin', 'sensitive-words'],
    type: 'string_list',
    placeholderKey: 'cfg.string_list_placeholder',
    keywords: ['devin', 'sensitive', 'words', 'obfuscate'],
  },

  // ── 7. Advanced & experimental ────────────────────────────────────────────
  {
    id: 'discoveryEnabled',
    sectionId: 'advanced',
    labelKey: 'cfg.f_discovery_enabled',
    descKey: 'cfg.f_discovery_enabled_desc',
    yamlPath: ['server', 'discovery', 'enabled'],
    type: 'switch',
    defaultValue: false,
    keywords: ['mdns', 'dns-sd', 'discovery', 'lan'],
  },
  {
    id: 'discoveryServiceName',
    sectionId: 'advanced',
    labelKey: 'cfg.f_discovery_service_name',
    descKey: 'cfg.f_discovery_service_name_desc',
    yamlPath: ['server', 'discovery', 'service-name'],
    type: 'string',
    placeholderKey: 'office',
    keywords: ['mdns', 'discovery', 'name'],
  },
  {
    id: 'discoveryAuthRequired',
    sectionId: 'advanced',
    labelKey: 'cfg.f_discovery_auth_required',
    descKey: 'cfg.f_discovery_auth_required_desc',
    // CPA reads an absent value as true.
    yamlPath: ['server', 'discovery', 'auth-required'],
    type: 'switch',
    defaultValue: true,
    keywords: ['mdns', 'discovery', 'auth'],
  },
  {
    id: 'discoveryAdvertiseManagement',
    sectionId: 'advanced',
    labelKey: 'cfg.f_discovery_advertise_mgmt',
    descKey: 'cfg.f_discovery_advertise_mgmt_desc',
    yamlPath: ['server', 'discovery', 'advertise-management'],
    type: 'switch',
    defaultValue: false,
    keywords: ['mdns', 'discovery', 'management'],
  },
  {
    id: 'pprofEnable',
    sectionId: 'advanced',
    labelKey: 'cfg.f_pprof_enable',
    descKey: 'cfg.f_pprof_enable_desc',
    yamlPath: ['observability', 'pprof', 'enable'],
    type: 'switch',
    defaultValue: false,
    keywords: ['pprof', 'profile', 'debug'],
  },
  {
    id: 'pprofAddr',
    sectionId: 'advanced',
    labelKey: 'cfg.f_pprof_addr',
    descKey: 'cfg.f_pprof_addr_desc',
    yamlPath: ['observability', 'pprof', 'addr'],
    type: 'string',
    placeholderKey: '127.0.0.1:8316',
    keywords: ['pprof', 'address', 'listen'],
  },

  // ── 8. Payload rules ────────────────────────────────────────────
  {
    id: 'payloadDefaultRules',
    sectionId: 'payload',
    labelKey: 'cfg.f_payload_default',
    descKey: 'cfg.f_payload_default_desc',
    yamlPath: ['requests', 'payload', 'default'],
    type: 'json_editor',
    keywords: ['payload', 'default'],
  },
  {
    id: 'payloadDefaultRawRules',
    sectionId: 'payload',
    labelKey: 'cfg.f_payload_default_raw',
    descKey: 'cfg.f_payload_default_raw_desc',
    yamlPath: ['requests', 'payload', 'default-raw'],
    type: 'json_editor',
    keywords: ['payload', 'raw', 'json'],
  },
  {
    id: 'payloadOverrideRules',
    sectionId: 'payload',
    labelKey: 'cfg.f_payload_override',
    descKey: 'cfg.f_payload_override_desc',
    yamlPath: ['requests', 'payload', 'override'],
    type: 'json_editor',
    keywords: ['payload', 'override'],
  },
  {
    id: 'payloadOverrideRawRules',
    sectionId: 'payload',
    labelKey: 'cfg.f_payload_override_raw',
    descKey: 'cfg.f_payload_override_raw_desc',
    yamlPath: ['requests', 'payload', 'override-raw'],
    type: 'json_editor',
    keywords: ['payload', 'override', 'raw'],
  },
  {
    id: 'payloadFilterRules',
    sectionId: 'payload',
    labelKey: 'cfg.f_payload_filter',
    descKey: 'cfg.f_payload_filter_desc',
    yamlPath: ['requests', 'payload', 'filter'],
    type: 'json_editor',
    keywords: ['payload', 'filter'],
  },
];
