package configyaml

// The tables below are data, not logic: they are CPA's own relocation table,
// taken from buildV8Paths and v8KeyFamilies in internal/config/config_v8.go of
// router-for-me/CLIProxyAPI at v8.0.2 (commit 4a2c818). CPA derives its leaf list
// by walking its Config struct, so a CPA release that adds or moves a setting
// changes this table; re-derive it from that file rather than editing entries by
// hand. docs/cpa-v8-compat.md records the procedure.

// CONFIG_LAYOUT_LEAF_RULES are the settings CPA moves one by one. A leaf is the
// unit of CPA's precedence rule: when both spellings of a leaf are present, the
// v8 one is used and the legacy one is deleted on the next load or save, even
// when the legacy value is a whole list or map.
var CONFIG_LAYOUT_LEAF_RULES = []LayoutRule{
	{Legacy: "antigravity-signature-bypass-strict", Current: "oauth.providers.antigravity.signature-bypass-strict"},
	{Legacy: "antigravity-signature-cache-enabled", Current: "oauth.providers.antigravity.signature-cache-enabled"},
	{Legacy: "antigravity.connection-pool.enabled", Current: "oauth.providers.antigravity.connection-pool.enabled"},
	{Legacy: "antigravity.connection-pool.idle-conn-timeout", Current: "oauth.providers.antigravity.connection-pool.idle-conn-timeout"},
	{Legacy: "antigravity.connection-pool.max-idle-conns-per-host", Current: "oauth.providers.antigravity.connection-pool.max-idle-conns-per-host"},
	{Legacy: "antigravity.sensitive-words", Current: "oauth.providers.antigravity.sensitive-words"},
	{Legacy: "api-keys", Current: "access.api-keys", LegacyKind: LegacyKindSequence},
	{Legacy: "auth-auto-refresh-workers", Current: "oauth.auth-auto-refresh-workers"},
	{Legacy: "auth-dir", Current: "oauth.auth-dir"},
	{Legacy: "claude-code.disable-cloaking-model-list", Current: "oauth.providers.claude.claude-code.disable-cloaking-model-list"},
	{Legacy: "claude-header-defaults.arch", Current: "oauth.providers.claude.header-defaults.arch"},
	{Legacy: "claude-header-defaults.os", Current: "oauth.providers.claude.header-defaults.os"},
	{Legacy: "claude-header-defaults.package-version", Current: "oauth.providers.claude.header-defaults.package-version"},
	{Legacy: "claude-header-defaults.runtime-version", Current: "oauth.providers.claude.header-defaults.runtime-version"},
	{Legacy: "claude-header-defaults.stabilize-device-profile", Current: "oauth.providers.claude.header-defaults.stabilize-device-profile"},
	{Legacy: "claude-header-defaults.timeout", Current: "oauth.providers.claude.header-defaults.timeout"},
	{Legacy: "claude-header-defaults.timezone", Current: "oauth.providers.claude.header-defaults.timezone"},
	{Legacy: "claude-header-defaults.user-agent", Current: "oauth.providers.claude.header-defaults.user-agent"},
	{Legacy: "claude.model-level-cooling", Current: "oauth.providers.claude.model-level-cooling"},
	{Legacy: "codex-header-defaults.beta-features", Current: "oauth.providers.codex.header-defaults.beta-features"},
	{Legacy: "codex-header-defaults.user-agent", Current: "oauth.providers.codex.header-defaults.user-agent"},
	{Legacy: "codex.disable-codex-cloaking", Current: "oauth.providers.codex.disable-codex-cloaking"},
	{Legacy: "codex.identity-confuse", Current: "oauth.providers.codex.identity-confuse"},
	{Legacy: "codex.live-media-relay.disable-private-remote-ips", Current: "oauth.providers.codex.live-media-relay.disable-private-remote-ips"},
	{Legacy: "codex.live-media-relay.enabled", Current: "oauth.providers.codex.live-media-relay.enabled"},
	{Legacy: "codex.live-media-relay.ice-servers", Current: "oauth.providers.codex.live-media-relay.ice-servers"},
	{Legacy: "codex.live-media-relay.max-sessions", Current: "oauth.providers.codex.live-media-relay.max-sessions"},
	{Legacy: "codex.live-media-relay.public-ip", Current: "oauth.providers.codex.live-media-relay.public-ip"},
	{Legacy: "codex.live-media-relay.udp-port-max", Current: "oauth.providers.codex.live-media-relay.udp-port-max"},
	{Legacy: "codex.live-media-relay.udp-port-min", Current: "oauth.providers.codex.live-media-relay.udp-port-min"},
	{Legacy: "codex.model-level-cooling", Current: "oauth.providers.codex.model-level-cooling"},
	{Legacy: "codex.optimize-multi-agent-v2", Current: "oauth.providers.codex.optimize-multi-agent-v2"},
	{Legacy: "codex.orphan-delegation-compatibility", Current: "oauth.providers.codex.orphan-delegation-compatibility"},
	{Legacy: "codex.response-steering", Current: "oauth.providers.codex.response-steering"},
	{Legacy: "codex.stream-bootstrap-buffering", Current: "oauth.providers.codex.stream-bootstrap-buffering"},
	{Legacy: "codex.stream-bootstrap-timeout", Current: "oauth.providers.codex.stream-bootstrap-timeout"},
	{Legacy: "commercial-mode", Current: "server.commercial-mode"},
	{Legacy: "credential-concurrency.busy-retry-max", Current: "credentials.concurrency.busy-retry-max"},
	{Legacy: "credential-concurrency.busy-retry-min", Current: "credentials.concurrency.busy-retry-min"},
	{Legacy: "credential-concurrency.cleanup-interval", Current: "credentials.concurrency.cleanup-interval"},
	{Legacy: "credential-concurrency.cpa-cancel-bound", Current: "credentials.concurrency.cpa-cancel-bound"},
	{Legacy: "credential-concurrency.cpa-heartbeat-timeout", Current: "credentials.concurrency.cpa-heartbeat-timeout"},
	{Legacy: "credential-concurrency.lifecycle-config-revision", Current: "credentials.concurrency.lifecycle-config-revision"},
	{Legacy: "credential-concurrency.max-limit", Current: "credentials.concurrency.max-limit"},
	{Legacy: "credential-concurrency.observation-barrier-revision", Current: "credentials.concurrency.observation-barrier-revision"},
	{Legacy: "credential-concurrency.reclaim-grace", Current: "credentials.concurrency.reclaim-grace"},
	{Legacy: "credential-concurrency.release-flush-interval", Current: "credentials.concurrency.release-flush-interval"},
	{Legacy: "credential-concurrency.release-max-backoff", Current: "credentials.concurrency.release-max-backoff"},
	{Legacy: "credential-in-flight.max-aggregate-groups", Current: "credentials.in-flight.max-aggregate-groups"},
	{Legacy: "credential-in-flight.max-details", Current: "credentials.in-flight.max-details"},
	{Legacy: "credential-in-flight.max-part-bytes", Current: "credentials.in-flight.max-part-bytes"},
	{Legacy: "credential-in-flight.max-part-count", Current: "credentials.in-flight.max-part-count"},
	{Legacy: "credential-in-flight.max-revision-bytes", Current: "credentials.in-flight.max-revision-bytes"},
	{Legacy: "credential-in-flight.max-string-bytes", Current: "credentials.in-flight.max-string-bytes"},
	{Legacy: "credential-in-flight.snapshot-interval", Current: "credentials.in-flight.snapshot-interval"},
	{Legacy: "credential-in-flight.staging-retention", Current: "credentials.in-flight.staging-retention"},
	{Legacy: "credential-in-flight.stale-after", Current: "credentials.in-flight.stale-after"},
	{Legacy: "debug", Current: "observability.logs.debug"},
	{Legacy: "devin.sensitive-words", Current: "oauth.providers.devin.sensitive-words"},
	{Legacy: "disable-claude-cloak-mode", Current: "oauth.providers.claude.disable-claude-cloak-mode"},
	{Legacy: "disable-cooling", Current: "routing.cooldown.disable-cooling"},
	{Legacy: "disable-image-generation", Current: "multimedia.disable-image-generation"},
	{Legacy: "discovery.advertise-management", Current: "server.discovery.advertise-management"},
	{Legacy: "discovery.auth-required", Current: "server.discovery.auth-required"},
	{Legacy: "discovery.enabled", Current: "server.discovery.enabled"},
	{Legacy: "discovery.interfaces.exclude", Current: "server.discovery.interfaces.exclude"},
	{Legacy: "discovery.interfaces.include", Current: "server.discovery.interfaces.include"},
	{Legacy: "discovery.service-name", Current: "server.discovery.service-name"},
	{Legacy: "discovery.service-type", Current: "server.discovery.service-type"},
	{Legacy: "discovery.subtypes", Current: "server.discovery.subtypes"},
	{Legacy: "error-logs-max-files", Current: "observability.logs.error-logs-max-files"},
	{Legacy: "force-model-prefix", Current: "routing.force-model-prefix"},
	{Legacy: "gpt-image-2-base-model", Current: "multimedia.gpt-image-2-base-model"},
	{Legacy: "host", Current: "server.host"},
	{Legacy: "logging-to-file", Current: "observability.logs.logging-to-file"},
	{Legacy: "logs-max-total-size-mb", Current: "observability.logs.logs-max-total-size-mb"},
	{Legacy: "max-retry-credentials", Current: "routing.retry.max-retry-credentials"},
	{Legacy: "max-retry-interval", Current: "routing.retry.max-retry-interval"},
	{Legacy: "nonstream-keepalive-interval", Current: "requests.nonstream-keepalive-interval"},
	{Legacy: "oauth-excluded-models", Current: "oauth.excluded-models"},
	{Legacy: "oauth-model-alias", Current: "oauth.model-alias"},
	{Legacy: "oauth-request-scoped-errors", Current: "oauth.request-scoped-errors"},
	{Legacy: "passthrough-headers", Current: "requests.passthrough-headers"},
	{Legacy: "payload.default", Current: "requests.payload.default"},
	{Legacy: "payload.default-raw", Current: "requests.payload.default-raw"},
	{Legacy: "payload.filter", Current: "requests.payload.filter"},
	{Legacy: "payload.override", Current: "requests.payload.override"},
	{Legacy: "payload.override-raw", Current: "requests.payload.override-raw"},
	{Legacy: "port", Current: "server.port"},
	{Legacy: "pprof.addr", Current: "observability.pprof.addr"},
	{Legacy: "pprof.enable", Current: "observability.pprof.enable"},
	{Legacy: "proxy-url", Current: "requests.proxy-url"},
	{Legacy: "quota-exceeded.antigravity-credits", Current: "oauth.providers.antigravity.antigravity-credits"},
	{Legacy: "redis-usage-queue-retention-seconds", Current: "observability.usage.redis-usage-queue-retention-seconds"},
	{Legacy: "remote-management.allow-remote", Current: "management.allow-remote"},
	{Legacy: "remote-management.base-url", Current: "management.base-url"},
	{Legacy: "remote-management.disable-auto-update-panel", Current: "management.disable-auto-update-panel"},
	{Legacy: "remote-management.disable-control-panel", Current: "management.disable-control-panel"},
	{Legacy: "remote-management.panel-github-repository", Current: "management.panel-github-repository"},
	{Legacy: "remote-management.secret-key", Current: "management.secret-key"},
	{Legacy: "request-log", Current: "observability.logs.request-log"},
	{Legacy: "request-retry", Current: "routing.retry.request-retry"},
	{Legacy: "save-cooldown-status", Current: "routing.cooldown.save-cooldown-status"},
	{Legacy: "streaming.bootstrap-retries", Current: "requests.streaming.bootstrap-retries"},
	{Legacy: "streaming.keepalive-seconds", Current: "requests.streaming.keepalive-seconds"},
	{Legacy: "tls.cert", Current: "server.tls.cert"},
	{Legacy: "tls.enable", Current: "server.tls.enable"},
	{Legacy: "tls.key", Current: "server.tls.key"},
	{Legacy: "transient-error-cooldown-seconds", Current: "routing.cooldown.transient-error-cooldown-seconds"},
	{Legacy: "trusted-proxies", Current: "server.trusted-proxies"},
	{Legacy: "usage-statistics-enabled", Current: "observability.usage.usage-statistics-enabled"},
	{Legacy: "video-result-auth-cache-ttl", Current: "multimedia.video-result-auth-cache-ttl"},
	{Legacy: "ws-auth", Current: "oauth.providers.aistudio.ws-auth"},
	{Legacy: "xai.inject-x-search", Current: "oauth.providers.xai.inject-x-search"},
}

// CONFIG_LAYOUT_SECTION_RULES are the legacy sections whose whole subtree moves.
// They place a section-level editor (the payload rule builder) and keep a path
// below a leaf, such as one payload category, in the same section as its leaf.
var CONFIG_LAYOUT_SECTION_RULES = []LayoutRule{
	{Legacy: "antigravity", Current: "oauth.providers.antigravity"},
	{Legacy: "antigravity.connection-pool", Current: "oauth.providers.antigravity.connection-pool"},
	{Legacy: "claude", Current: "oauth.providers.claude"},
	{Legacy: "claude-code", Current: "oauth.providers.claude.claude-code"},
	{Legacy: "claude-header-defaults", Current: "oauth.providers.claude.header-defaults"},
	{Legacy: "codex", Current: "oauth.providers.codex"},
	{Legacy: "codex-header-defaults", Current: "oauth.providers.codex.header-defaults"},
	{Legacy: "codex.live-media-relay", Current: "oauth.providers.codex.live-media-relay"},
	{Legacy: "credential-concurrency", Current: "credentials.concurrency"},
	{Legacy: "credential-in-flight", Current: "credentials.in-flight"},
	{Legacy: "devin", Current: "oauth.providers.devin"},
	{Legacy: "discovery", Current: "server.discovery"},
	{Legacy: "discovery.interfaces", Current: "server.discovery.interfaces"},
	{Legacy: "payload", Current: "requests.payload"},
	{Legacy: "pprof", Current: "observability.pprof"},
	{Legacy: "remote-management", Current: "management"},
	{Legacy: "streaming", Current: "requests.streaming"},
	{Legacy: "tls", Current: "server.tls"},
	{Legacy: "xai", Current: "oauth.providers.xai"},
}

// PROVIDER_KEY_FAMILY_RULES are the upstream credential lists. They move under
// the root api-keys mapping and change shape on the way (one group per legacy
// entry, with the key material in a nested keys list), so no path rewrite can
// translate them; OMC edits them only through CPA's per-family endpoints.
var PROVIDER_KEY_FAMILY_RULES = []LayoutRule{
	{Legacy: "gemini-api-key", Current: "api-keys.gemini"},
	{Legacy: "interactions-api-key", Current: "api-keys.interactions"},
	{Legacy: "vertex-api-key", Current: "api-keys.vertex"},
	{Legacy: "codex-api-key", Current: "api-keys.codex"},
	{Legacy: "claude-api-key", Current: "api-keys.claude"},
	{Legacy: "xai-api-key", Current: "api-keys.xai"},
	{Legacy: "meta-api-key", Current: "api-keys.meta"},
	{Legacy: "openai-compatibility", Current: "api-keys.openai-compatibility"},
}
